restylers:
  - clang-format:
      enabled: false
  - prettier:
      include:
        - "src/**/*.ts"
  - prettier-json:
      enabled: false # use jq
  - whitespace:
      include:
        - "**/*"
        - "!dist/index.js"
  - "*"
