name: "Wiz"
description: "Action to run Wiz CLI and format/report results"
author: "Freckle"
inputs:
  wiz-client-id:
    description: "Wiz Service Account Client Id"
    required: true
  wiz-client-secret:
    description: "Wiz Service Account Client Secret"
    required: true
  wiz-api-endpoint-url:
    description: "Wiz API Endpoint URL, such as https://api.us19.app.wiz.io/graphql"
    required: false
  wiz-api-idp:
    description: "IdP used for Wiz API, Auth0 or Cognito. Only needed if your account has not migrated to Cognito yet."
    required: false
    default: "cognito"
  image:
    description: "Image to scan"
    required: true
  custom-policies:
    description: "Custom policies, comma-separated names"
    required: false
  fail:
    description: "Fail if image does not satisfy policy?"
    required: true
    default: "true"
  pull:
    description: "Pull the image before scanning?"
    required: true
    default: "false"
outputs:
  scan-id:
    description: "Id of Scan Report"
  scan-url:
    description: "URL of Scan Report"
  scan-result:
    description: "Outcome of scan, one of passed|failed|error"
runs:
  using: "node20"
  main: "dist/index.js"
